### ISSUE TITLE
STANDALONE mode does not load current Team/Roster XML from FUMBBL correctly

### ISSUE THREAD

**Issue by cmelchior** [christerk/ffb#76]
Trying to set up the server in STANDALONE mode and importing a team from FUMBBL I ran into some issues, that looks like bugs.

To reproduce:

1. Fetch the XML for a Team on FUMBBL, e.g. `https://fumbbl.com/xml:team?id=1158751`
2. Copy it as file to `/ffb-server/teams/human_team.xml`
3. Note it has the rosterId: `4964`
4. Trying to fetch that roster using this endpoint fails: `https://fumbbl.com/xml:roster?id=4964` (I guess this is working as intended)
5. Fetch the roster data using `https://fumbbl.com/xml:roster?team=1158751` and copy it to `/ffb-server/teams/test_human_roster.xml` (note that it has an <roster id="1158751">.
6. Start the server in `standalone` mode.
7. Start a test game with the team that was copied. (using coach `cmelchior`)
7. The server will now log this crash:

```
2024-10-07T07:48:18.146 -------- ---- 	at com.fumbbl.ffb.server.RosterCache.getRosterById(RosterCache.java:34)
2024-10-07T07:48:18.146 -------- ---- 	at com.fumbbl.ffb.server.GameCache.updateRoster(GameCache.java:246)
2024-10-07T07:48:18.146 -------- ---- 	at com.fumbbl.ffb.server.GameCache.lambda$getTeamsForCoach$1(GameCache.java:305)
2024-10-07T07:48:18.146 -------- ---- 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
2024-10-07T07:48:18.146 -------- ---- 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
2024-10-07T07:48:18.146 -------- ---- 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
2024-10-07T07:48:18.146 -------- ---- 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
2024-10-07T07:48:18.146 -------- ---- 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
2024-10-07T07:48:18.146 -------- ---- 	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
2024-10-07T07:48:18.146 -------- ---- 	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
2024-10-07T07:48:18.146 -------- ---- 	at com.fumbbl.ffb.server.GameCache.getTeamsForCoach(GameCache.java:305)
2024-10-07T07:48:18.146 -------- ---- 	at com.fumbbl.ffb.server.handler.ServerCommandHandlerJoinApproved.sendTeamList(ServerCommandHandlerJoinApproved.java:256)
2024-10-07T07:48:18.146 -------- ---- 	at com.fumbbl.ffb.server.handler.ServerCommandHandlerJoinApproved.handleCommand(ServerCommandHandlerJoinApproved.java:110)
2024-10-07T07:48:18.146 -------- ---- 	at com.fumbbl.ffb.server.handler.ServerCommandHandlerFactory.handleCommand(ServerCommandHandlerFactory.java:46)
2024-10-07T07:48:18.146 -------- ---- 	at com.fumbbl.ffb.server.net.ServerCommunication.handleCommandInternal(ServerCommunication.java:131)
2024-10-07T07:48:18.146 -------- ---- 	at com.fumbbl.ffb.server.net.ServerCommunication.run(ServerCommunication.java:106)
2024-10-07T07:48:18.146 -------- ---- 	at java.base/java.lang.Thread.run(Thread.java:1583)
```

Looking at the code, the behaviour makes sense since the new roster API doesn't have an ID that matches `<rosterId>` but matches team id instead. It is avery easy to fix, but it raises a few questions:

1. Is it intended that the standalone mode should not be able to load current rosters from FUMBBL?

2. Should the standalone roster loading mechanism be backwards compatible? I.e. if I provide a fix, should it still be able to load the old XML format? 

3. All the team/roster/setup information looks outdated, are they actively being used for anything? I guess the question is if I provide a patch for the roster loading, should I delete/update these? E.g. all the setup files need to adjust their values (it looks like they are off-by-one).

**Comment by SanityResort** [comment]
Just had a look at the RosterCache and yes, that is currently not working with the fumbbl xmls out of the box. So far I did not bother with it as you can easily add the roster id to the xml when needed and the live mode looks up the roster per team anyways.

If you feel like adding a fix for that go ahead. As long as the existing teams still work afterwards it should not matter how they are looked up. Just make sure your change only affects standalone mode.

I use the existing teams for local testing all the time. I am aware the stats are not in syn with the official ones but that does not matter much. But what do you mean by the setup files being off-by-one? Setups are linked to team ids, so changes in roster ids or the actual values in the teams should not affect that. 

From my side I do not see any need or much benefit from updating the teams but feel free if you want to.
